cenarios = {"CENÁRIO ESCRITÓRIO 01": 'ESTARÁ FELIZ DA VIDA NO ESCRITÓRIO DO IFOOD, OLHANDO PELA JANELINHA', "CENÁRIO ESCRITÓRIO 02":"VOCÊ VIROU UM FARIA LIMER, TRABALHANDO EM ALGUM BANCO DIGITAL POR LÁ",'CENÁRIO CASINHA 01':'VOCÊ INFELIZMENTE CONTINUA DESEMPREGADO POR CONTA DA PROCRASTINAÇÃO, MAS COM VONTADE DE MUDAR E CONTINUAR NA CARREIRA','CENÁRIO CASINHA 02':'VOCÊ INFELIZMENTE CONTINUA DESEMPREGADO POR CONTA DA PROCRASTINAÇÃO E DESISTIU DA CARREIRA','CENÁRIO HOSPITAL 01':'VOCÊ SOFREU BURNOUT, MAS VAI SOBREVIVER','CENÁRIO HOSPITAL 02':'VOCÊ INFARTOU E INFELIZMENTE MORREU'}

print(cenarios)
print("-------------------------------")
print(cenarios["CENÁRIO HOSPITAL 02"])